---
title: "REM Maps using Lidar Data"
date: "2025-02-03"
---

#tutorial source: https://www.youtube.com/watch?v=x8is770F7Og&ab_channel=MilosMakesMaps

```{R}
#1. Install packages
#install.packages("devtools")

#devtools::install_github("ropensci/terrainr")

pacman::p_load(
    terrainr, terra,
    sf, osmdata, classInt,
    ggplot2, rayshader, gstat
) 
#p_load install and load remaining library
#terrainr to fetch tiles
#terra for working with raster data
#sf needed for simple features/polygons/rivers
#river data from OSM
#calculate digital elevation model breaks using classInt
#visualise using ggplot2
#2D to 3D map using rayshader
#gstat for spatial and spatio-temporal geostatistical modelling
```

```{R}
#2. Define Area
#data source: https://apps.nationalmap.gov/lidar-explorer/#/
#select DEM at 1 meter
#find bounding box for the region of interest

#-110.621713,43.750439,-110.573660,43.781138

xmin <- -110.621713
ymin <- 43.750439
xmax <- -110.573660
ymax <- 43.781138

#create bounding box
#st_sfc creates simple feature geometry list column, set class and add coordinate reference system
bb <- sf::st_sfc(
    sf::st_polygon(
        list(
            cbind(
                c(xmin, xmax, xmax, xmin, xmin),
                c(ymin, ymin, ymax, ymax, ymin)
            )
        )
    ),
    crs = 4326
)

```


```{R}
#3. Get LIDAR DATA
dem <- terrainr::get_tiles(
    data = bb,
    output_prefix = "rem",
    side_length = 8e3, #return a single tile of the area by increasing side length
    resolution = 1, #resolution of 1 metre
    services = "elevation", #specify elevation for DEM
    verbose = TRUE #provide information on the tiles downloaded
)

dem_rast <- terra::rast("rem_3DEPElevation_1_1.tif")
```

```{R}
#4. Get River Line

#use OSM data to get the river feature
#opq is to build an Overpass query to access OSM database
#key = waterway and need to specify it is a river and not other features
#osmdata_sf will return the object as a simple feature
river <- osmdata::opq(
    bbox = bb
) |>
    osmdata::add_osm_feature(
        key = "waterway",
        value = "river"
    ) |>
    osmdata::osmdata_sf()

#need the line specifically which intersect with the bounding box
#union all the line segments
#cast the multilinestring from union into a linestring to get as many values for many segments
river_sf <- river$osm_lines |>
    sf::st_intersection(
        bb
    ) |>
    sf::st_union() |>
    sf::st_cast(
        "LINESTRING"
    ) |>
    sf::st_as_sf()

#create a quick plot of the raster and the river
#st_geometry to plot the geometry of the river
terra::plot(dem_rast)
plot(
    sf::st_geometry(
        river_sf
    ),
    col = "white",
    add = TRUE
)


```

```{r}
#5. Extract elevation values
#decrease the resolution by 5x to improve processing time
#can ignore if don't mind waiting
dem_rast_agg <- terra::aggregate(
    dem_rast,
    fact = 5
)

#extract the value for the river
river_elev <- terra::extract(
    x = dem_rast_agg,
    y = terra::vect(river_sf), #terra::vect makes it into a terra friendly format
    xy = TRUE, #transform the resulting dataframe with x and y values
    na.rm = TRUE #remove missing values
) |>
    na.omit() #extra step to remove na values

#rename 2nd column
names(river_elev)[2] <- "elevation"
nrow(river_elev)
```

```{r}
#6. Define Model
#define interpolation model to predict values for specific river segment
#formula where elevation is the dependent variable/attribute being interpolated while 1 means there are no predictor/independent variables and this is a spatial interpolation rather than regression model
#x and y are the variables used to determine where each elevation measurement is located
#nmax defines how many points to use for prediction which is the maximum number of points
idw_model <- gstat::gstat(
    formula = elevation ~ 1,
    locations = ~ x + y,
    data = river_elev,
    nmax = nrow(river_elev)
)

```


```{r}
#7. Predict values from IDW model
#3 arguments required which include 1) what is used for interpolation, 2) underlying model for prediction and the coordinate reference system
river_surface <- terra::interpolate(
    dem_rast_agg,
    idw_model,
    crs = terra::crs(dem_rast_agg)
)


```

```{r}
#8. REM
#rem = dem - river elevation
rem <- dem_rast_agg - river_surface

#resample back to dem_rast to increase resolution
rem_final <- terra::resample(
    rem, dem_rast
)

```


```{r}
#9. Final Preparation
#transform raster file into a dataframe
#ignore lyr2 used for interpolation
rem_df <- as.data.frame(
    rem_final,
    xy = TRUE
)

head(rem_df)

#rename lyr1 column as elevation
names(rem_df)[3] <- "elevation"

#use log values to create more variation in the values. This is a very small value so no log0 issue
epsilon <- 1e-10

#create a new column called elevation_log
#normalise value using pmax
rem_df$elevation_log <- log1p(
    pmax(
        rem_df$elevation, epsilon
    )
)

#to create variation in the values, use natural breaks
breaks <- classInt::classIntervals(
    rem_df$elevation_log,
    n = 12,
    style = "fisher"
)$brks #to get the breaks

#use artsy palette
cols <- hcl.colors(
    palette = "Mako",
    12, rev = TRUE #reverse so lighter values are associated with river elevation and darker with the elevation around
)

#inspect how the colours look like
pie(rep(
    1, length(cols)
), col = cols)

#use value 1 and 8 to 12 inclusive
pal <- cols[c(1, 8:12)]

#make piechart to see colours selected
pie(rep(
    1, length(pal)
), col = pal)

theme_for_the_win <- function() {
    theme_minimal() +
        theme(
            axis.line = element_blank(),
            axis.title.x = element_blank(),
            axis.title.y = element_blank(),
            axis.text.x = element_blank(),
            axis.text.y = element_blank(),
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            legend.position = "none",
            plot.background = element_rect(
                fill = "white", color = NA
            ),
            plot.margin = unit(
                c(
                    t = 0, r = 0,
                    l = 0, b = 0
                ), "cm"
            )
        )
}
#decrease plot margin so more space for the map
#0 margin for top, right, left and bottom side

#define data, need to define x, y and filling raster pixels for the aesthetics
rem_plot <- ggplot(
    rem_df, aes(
        x = x, y = y,
        fill = elevation_log
    )
) +
    geom_raster() +
    scale_fill_gradientn(
        breaks = breaks,
        colours = pal,
        name = ""
    ) +
    theme_for_the_win()
#define the palette and breaks for the raster
#scale_fill_gradietn since continuous
```


```{r}
#11. 3D plot
width <- ncol(rem_final) / 500
height <- nrow(rem_final) / 500

rayshader::plot_gg(
    ggobj = rem_plot,
    width = width,
    height = height,
    windowsize = c(
        width * 75,
        height * 75
    ),
    scale = 75,
    solid = FALSE,
    shadow = FALSE,
    shadow_intensity = 1,
    phi = 87,
    theta = 0,
    zoom = .64,
    multicore = TRUE
)

rayshader::render_camera(
    zoom = .545
)

u <- "https://dl.polyhaven.org/file/ph-assets/HDRIs/hdr/4k/rosendal_plains_2_4k.hdr"
hdri_file <- basename(u)

download.file(
    url = u,
    destfile = hdri_file,
    mode = "wb"
)

rayshader::render_highquality(
    filename = "3d-snake-river.png",
    preview = TRUE,
    light = FALSE,
    environment_light = hdri_file,
    intensity = .85,
    rotate_env = 90,
    parallel = TRUE,
    width = width * 500,
    height = height * 500,
    interactive = FALSE
)
```