---
title: "3Precipitation"
date: "2024-05-19"
---

#Tutorial Source: https://www.youtube.com/watch?v=9Ex-f66qe2w

#1 install and load packages
```{r setup}
#if package is not installed, to install it
if(
    !require("pacman")
){
    install.packages("pacman")
}

pacman::p_load(
    pRecipe, #download 27 different precipitation datasets
    giscoR, #geospatial data repository
    terra, #raster file
    tidyverse, #data wrangling
    rayshader, #data visualisation
    sf, #simple features
    classInt #choose univariate class intervals
)
```

#2 country extent
```{r}
country_sf <- giscoR::gisco_get_countries(
    country = "CH",
    resolution = "1"
)
```


#3 precipitation data
```{r}
pRecipe::download_data(
    dataset = "mswep", #crisp resolution .25 degrees and global extent from 1979 to 2023
    path = getwd(), #save to working direction
    domain = "raw", 
    timestep = "yearly" #temporal level of analysis
)

list.files()

mswep_data <- terra::rast(
    "mswep_tp_mm_global_197902_202301_025_yearly.nc" #name of file from list.files()
) |>
terra::crop( #crop to country extent
    country_sf
)

terra::plot(mswep_data[[1]]) #as 45 layers, just take the first layer
plot(sf::st_geometry(country_sf), add = TRUE)
```


#4. panel precipitation
```{r}
names(mswep_data) <- 1979:2023 #file names from 1979 to 2023

mswep_df <- mswep_data |>
    as.data.frame(xy = TRUE) |> #transform into dataframe so it can be plot in ggplot2
#xy=True to return coordinates
    tidyr::pivot_longer( #long format
        !c("x", "y"), #exclude x and y from the operation
        names_to = "year", #create year column
        values_to = "precipitation"
    ) |>
    dplyr::filter(year != 2023) #2023 dataset is not complete hence remove it

head(mswep_df)
```


#5. theme, breaks and colours for panel map
```{r}
theme_for_the_win <- function(){ #create blank theme and keep items as blank
    theme_minimal() +
    theme(
        axis.line = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        legend.position = "right", #position legend at right
        legend.title = element_text(
            size = 11, color = "grey10"
        ), #need to tell ggplot2 this is a text
        legend.text = element_text(
            size = 10, color = "grey10"
        ),
        panel.grid.major = element_line(
            color = NA
        ),
        panel.grid.minor = element_line(
            color = NA
        ),
        plot.background = element_rect(
            fill = NA, color = NA
        ),
        legend.background = element_rect(
            fill = "white", color = NA
        ),
        panel.border = element_rect(
            fill = NA, color = NA
        ),
        plot.margin = unit(
            c(
                t = 0, r = 0,
                b = 0, l = 0
            ), "lines"
        )
    )
}

#use natural intervals
breaks <- classInt::classIntervals(
    mswep_df$precipitation, #name of dataframe and column of data
    n = 5,
    style = "equal"
)$brks #access breaks

colors <- hcl.colors( #base colours
    n = length(breaks), #number of colour is length of the breaks
    palette = "Temps", #used for temperature
    rev = TRUE #to have it in proper order, need to reverse colour palette
)
```


#6 2D panel map
```{r}
map1 <- ggplot(
    data = mswep_df
) +
geom_raster(
    aes(
        x = x,
        y = y,
        fill = precipitation
    )
) +
geom_contour( #add contour lines
    aes(
       x = x,
       y = y,
       z = precipitation 
    ), color = "white" # add this line
) +
geom_sf( #add country boundaries
    data = country_sf,
    fill = "transparent",
    color = "grey10",
    size = .5
) +
scale_fill_gradientn( #since continuous use scale_fill_gradientn
    name = "mm", #units for precipitation is mm
    colors = colors,
    breaks = breaks,
    labels = round(breaks, 0), # use round(breaks, 0)
    limits = c( #both the highest and lowest precipitation data taken into account when creating breaks
        min(mswep_df$precipitation),
        max(mswep_df$precipitation)
    )
) +
facet_wrap(~year) + #create a separate map for every year
guides(
    fill = guide_colourbar(
        direction = "vertical",
        barheight = unit(50, "mm"),
        barwidth = unit(5, "mm"),
        title.position = "top",
        label.position = "right",
        title.hjust = .5,
        label.hjust = .5,
        ncol = 1,
        byrow = FALSE
    )
) +
theme_for_the_win()
```

#7. average precipitation
```{r}
mswep_average_df <- mswep_df |>
    dplyr::group_by( #group by coordinates
        x, y, .drop = FALSE
    ) |>
    dplyr::summarise( #create average
        mean = mean(precipitation)
    )

head(mswep_average_df)

#create breaks as above
#note dataframe and column name is different
breaks <- classInt::classIntervals(
    mswep_average_df$mean,
    n = 5,
    style = "equal"
)$brks

colors <- hcl.colors(
    n = length(breaks),
    palette = "Temps",
    rev = TRUE
)

map2 <- ggplot(
    data = mswep_average_df
) +
geom_raster(
    aes(
        x = x,
        y = y,
        fill = mean
    )
) +
geom_contour(
    aes(
       x = x,
       y = y,
       z = mean 
    ), color = "white" # add this line
) +
geom_sf(
    data = country_sf,
    fill = "transparent",
    color = "grey10",
    size = .5
) +
scale_fill_gradientn(
    name = "mm",
    colors = colors,
    breaks = breaks, 
    labels = round(breaks, 0), # use round(breaks, 0)
    limits = c(
        min(mswep_average_df$mean),
        max(mswep_average_df$mean)
    )
) +
guides(
    fill = guide_colourbar(
        direction = "vertical",
        barheight = unit(50, "mm"),
        barwidth = unit(5, "mm"),
        title.position = "top",
        label.position = "right",
        title.hjust = .5,
        label.hjust = .5,
        ncol = 1,
        byrow = FALSE
    )
) +
theme_for_the_win()
```

#8. 3D Contour Map
```{r}
rayshader::plot_gg(
    ggobj = map2, #turn ggobject to 3D object
    width = 7,
    height = 7,
    scale = 250,
    solid = FALSE,
    shadow = TRUE,
    shadowcolor = "white",
    shadowwidth = 0,
    shadow_intensity = 1,
    window.size = c(600, 600),
    zoom = .7,
    phi = 85,
    theta = 0
)

rayshader::render_camera(
    phi = 60,
    theta = 30    
)
```

#9. render objects
```{r}
u <- "https://dl.polyhaven.org/file/ph-assets/HDRIs/hdr/4k/air_museum_playground_4k.hdr"

hdri_file <- basename(u)

download.file(
    url = u,
    destfile = hdri_file,
    mode = "wb"
)

rayshader::render_highquality(
    filename = "switzerland-average-precipitation.png",
    preview = TRUE,
    interactive = FALSE,
    parallel = TRUE,
    light = TRUE,
    environment_light = hdri_file,
    intensity = .45,
    rotate_env = 90,
    width = 2000,
    height = 2000
)
```
